#/bin/bash
echo "$(tput setaf 2)         █████████████████ $(tput sgr 0)"
echo "$(tput setaf 2)        ██               ██ $(tput sgr 0)"
echo "$(tput setaf 2)        ██               ██ $(tput sgr 0)"
echo "$(tput setaf 2)        ██               ██ $(tput sgr 0)"
echo "$(tput setaf 4)  ███████████████████████████████ $(tput sgr 0)"
echo "$(tput setaf 4)██$(tput setaf 3)                              $(tput setaf 4) ██ $(tput sgr 0)"
echo "$(tput setaf 4)██$(tput setaf 3)    //////////  //////////    $(tput setaf 4) ██ $(tput sgr 0)      $(tput setaf 3)  ____      _       _             $(tput setaf 6)    _                    "
echo "$(tput setaf 4)██$(tput setaf 3) (((///////// ////////////((( $(tput setaf 4) ██ $(tput sgr 0)      $(tput setaf 3) / ___|___ | | __ _| |__         $(tput setaf 6)    / \   _ __  _ __  ___ "
echo "$(tput setaf 4)██$(tput setaf 3)(((((        ////        (((((($(tput setaf 4)██ $(tput sgr 0)      $(tput setaf 3)| |   / _ \| |/ _  |  _ \ $(tput setaf 5)  _____ $(tput setaf 6)  / _ \ |  _ \|  _ \/ __| "
echo "$(tput setaf 4)██$(tput setaf 3)((((        /////         ((((($(tput setaf 4)██ $(tput sgr 0)      $(tput setaf 3)| |__| (_) | | (_| | |_) |$(tput setaf 5) |_____| $(tput setaf 6)/ ___ \| |_) | |_) \__ \ "
echo "$(tput setaf 4)██$(tput setaf 3)(((((        ////*       (((((($(tput setaf 4)██ $(tput sgr 0)      $(tput setaf 3) \____\___/|_|\__,_|_.__/     $(tput setaf 6)    /_/   \_\ .__/| .__/|___/"
echo "$(tput setaf 4)██$(tput setaf 3) (((///////// //((((((((((((( $(tput setaf 4) ██ $(tput sgr 0)      $(tput setaf 6)                                          |_|   |_|        "
echo "$(tput setaf 4)██$(tput setaf 3)    /////////.  ,(((((((((    $(tput setaf 4) ██ $(tput sgr 0)"
echo "$(tput setaf 4)██$(tput setaf 3)                              $(tput setaf 4) ██ $(tput sgr 0)"
echo "$(tput setaf 4) ██                             ██ $(tput sgr 0)"
echo "$(tput setaf 4) ███                          ███ $(tput sgr 0)"
echo "$(tput setaf 4)   ████████████████████████████ $(tput sgr 0)"
echo ""
echo "$(tput setaf 6)=========================================================================================================$(tput sgr 0)"
echo "$(tput setaf 6) Script Made By Yui Sakura $(tput sgr 0)"                  
echo "$(tput setaf 6) Subscribe To My Channel: https://bit.ly/3u4gpbQ"
echo "$(tput setaf 6) Follow Me On Facebook: https://bit.ly/3LAPF8U"
echo "$(tput setaf 6)=========================================================================================================$(tput sgr 0)"
echo "$(tput setaf 6) $(tput setaf 4) Hello, What Do You Want To Do?"
/home/colab/Colab-Apps/colab-apps.sh
