#!/bin/bash
/home/colab/Colab-Apps/Dependencies/logo
echo "$(tput setaf 6)"
echo "Select Video Editor You Want To Install:"
PS3='Please enter your choice: '
options=("Adobe After Effects CS6" "Wondershare Filmora X" "Go Back To Software Category Lists")
select selected in "${options[@]}"; do
    case $selected in
        "Adobe After Effects CS6")
		clear
		/home/colab/Colab-Apps/Softwares/AdobeAfterEffectsCS6/select
		break
            ;;
        "Wondershare Filmora X")
            ;;
        "Go Back To Software Category Lists")
		clear
		/home/colab/Colab-Apps/Dependencies/softwares
	    break
            ;;
        *) echo "Invalid Option ╯︿╰ $REPLY";;
    esac
done